<a href="https://colab.research.google.com/github/gagabriela2787/procesamientodedatos/blob/main/numpyej.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

Proceso de instalación


Creacion de arreglos a partir de listas


Con numeros prefijados


Con numeros aleatorios

In [ ]:
#importar numpy
import numpy as np


In [ ]:
#crear un arreglo unidimesional
arreglo1=np.array([1,2,3,4,5])
print(arreglo1)

[1 2 3 4 5]


In [ ]:
#crear arreglo de dos dimensiones
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
arreglo3=np.array([matrix, matrix])
print(arreglo3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#uso de arange
a=np.arange(1,11)
print(a)

print("ndim: ", a.ndim)
print("shape:", a.shape)
print("size: ", a.size)


[ 1  2  3  4  5  6  7  8  9 10]
ndim:  1
shape: (10,)
size:  10


Ejercicio:
Crear una matriz de 3 filas y 5 columnas,

 completados con los numeros del 1 al 15.


In [ ]:
matriz = np.arange(1, 10).reshape(3, 3)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("ndim: ", matriz.ndim)
print("shape:", matriz.shape)
print("size: ", matriz.size)

ndim:  2
shape: (3, 3)
size:  9


In [ ]:
# creando un arreglo con 0
arreglo=np.zeros((4,5))
print(arreglo)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print("ndim: ", arreglo.ndim)
print("shape:", arreglo.shape)
print("size: ", arreglo.size)

In [ ]:
# hacer lo mismo pero con una matriz

In [ ]:
#creando un arreglo con 1
arreglo=np.ones((2,3))
print(arreglo)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creando un arreglo con un mismo numero
arreglo=np.full(9,3)
print(arreglo)

[3 3 3 3 3 3 3 3 3]


In [ ]:
#Crear un arreglo con valores uniformemente espaciados
arreglo=np.linspace(1, 2, 5)
print(arreglo)

[1.   1.25 1.5  1.75 2.  ]


Crear un matrix de 4 filas y 5 columnas




, lleno completamente del mismo valor 5.


# Numeros aleatorios con NumPy

In [ ]:
# generar arreglo con nros enteros valor inicial,valor final, tamaño
x = np.random.randint(1,10,size=10)

print(x)


[1 5 7 8 6 3 7 4 3 7]


In [ ]:
#nros aleatorios entre 0 y 1
b=np.random.rand(25)
print(b)

[0.44827754 0.68381969 0.50540853 0.18387021 0.55773686 0.19458879
 0.68872373 0.64164916 0.0801064  0.68500364 0.22740472 0.76408484
 0.8719107  0.01999266 0.43939642 0.18842023 0.03406584 0.63154051
 0.80054821 0.31288186 0.28997604 0.26548087 0.98652673 0.74183314
 0.98731478]


Crear un arreglo tipo matriz de 5 filas y 3 columnas con numeros aleatorios entre 5 y 6.

# Operando sobre arreglos

In [ ]:
a=np.array([1,2,3,4,5])

b=a**3

print(b)

[  1   8  27  64 125]


In [ ]:
#podemos operar vectorialmente, siempre que sean de las mismos tamaños
c=np.array([6,7,8,9,10])

d=a+c

print(d)

[ 7  9 11 13 15]


In [ ]:
arr = np.array([1,2,3,4,5])
random_elements = np.random.choice(arr, size=(7,9))

print(random_elements)

[[4 3 2 4 2 2 4 3 2]
 [5 4 3 2 3 1 3 3 1]
 [5 4 2 2 5 5 4 2 1]
 [2 4 5 3 4 3 3 5 1]
 [3 4 5 5 1 5 1 4 4]
 [4 3 4 4 1 2 3 4 4]
 [5 4 2 1 3 3 2 1 4]]


Ejercicio crear una arreglo con los primeros 11 nros primos, y luego usarlo como insumo para generar una matriz de 4 filas y 7 columnas

In [ ]:
arr= np.array([2,3,5,7,11,13,17,19,23,29,31])
random_elements=np.random.choice(arr,size=(4,7))
print(random_elements)

[[11 31  5 29 29 31  3]
 [19  5 13 29 13 11 29]
 [19 29  5 31 11 17  5]
 [ 3 17  3  2  7  3 17]]


#Manipulando arrays
De manera muy parecida a las listas, los ndarrays permiten hacer slicing con []. Sus índices empiezan en 0.



In [ ]:
matrix_cool = np.arange(9).reshape(3, 3)
print(matrix_cool)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(matrix_cool[1,2])


5


In [ ]:
print(matrix_cool[0, :])


[0 1 2]


In [ ]:
print(matrix_cool[:, 1])


[1 4 7]


In [ ]:
print(matrix_cool[0:2, 0:2])


[[0 1]
 [3 4]]


In [ ]:
print(matrix_cool[:, :])


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Crear un arreglo de nro enteros aleatorios, entre 1 y 100,de 5 filas por 5 columnas, y devolver la matriz central de 3x3 elementos

In [ ]:
matriz = np.random.randint(1, 101, size=(5, 5))

print("Matriz original:")
print(matriz)


matriz_central = matriz[1:4, 1:4]

print("\nMatriz central:")
print(matriz_central)

Matriz original:
[[57 74 77 31  3]
 [67  8 37  2 71]
 [81 94 55 54 81]
 [58 75 53 18 42]
 [15 23 64 28 44]]

Matriz central:
[[ 8 37  2]
 [94 55 54]
 [75 53 18]]


#Estadística

In [ ]:
height_list = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75]
print(np.mean(height_list))
print(np.median(height_list))
print(np.std(height_list))

In [ ]:
#minimos y maximos 
print(np.max(height_list))
print(np.min(height_list))

.rand() y .uniform()
.rand(): números aleatorios en una distribución uniforme. Permite crear ndarrays.
.uniform(): igual que rand, pero permite ingresar los límites de la muestra.

# Distribuciones


In [ ]:
rand = np.random.rand(10000)
plt.hist(rand, bins=50)
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

uniform = np.random.uniform(low=18, high=90, size=10000)
plt.hist(uniform, bins=50)
plt.show()

In [ ]:
normal = np.random.normal(0, 3, 10000)
plt.hist(normal, bins=50)
plt.title('Distribución normal')

plt.show()

In [ ]:
arr = np.random.randint(1, 101, size=(5, 5))
print(arr)
print("__________________________")
matriz_cen = arr[1:4, 1:4]
print(matriz_cen)

In [ ]:
arr = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23,29,31])
random_elements = np.random.choice(arr, size=(4,7))

print(random_elements)